hosts:
- ipmi:
    vendor: lenovo                  # vendor name [dell, lenovo, hpe]
    address: 10.172.70.186          # IPMI address
    username: username              # IPMI username
    password: password              # IPMI password
  esxi:
    esxi_disk: ThinkSystem M.2      # ESXi os disk model or WWN ID
    password: password              # ESXi root user password
    address: 10.172.69.86           # ESXi Management Network IP address
    gateway: 10.172.64.1            # ESXi Management Network gateway
    netmask: 255.255.240.0          # ESXi Management Network netmask
    hostname: esxi-69-86            # ESXi hostname (option)
    dns:8.8.8.8,8.8.4.4             # ESXi DNS Servers    
    mgtnic: vmnic0                  # ESXi vSwitch0's nic device, can be set to vmnic name or mac address


- ipmi:
    vendor: dell
    address: 10.172.18.191
    username: username
    password: password
  esxi:
    esxi_disk: DELLBOSS VD
    password: password
    address: 10.172.18.95
    gateway: 10.172.16.1
    netmask: 255.255.240.0
    mgtnic: B4:96:91:A7:3F:D6
