---
- hosts: localhost
  name: Check inventory
  gather_facts: false
  tasks:
  - name: Check if the inventory host is empty
    vars:
      host_nums : "{{ groups['all'] | length }}"
    fail:
      msg: "{{ host_nums }} inventory is empty, please check your inventory.ini file"
    when: host_nums == "0"
  tags:
  - pre-check

- hosts: all
  name: Precheck redfish login
  gather_facts: false
  tasks:
  - name: Getting system inventory
    community.general.redfish_info:
      category: Systems
      command: GetSystemInventory
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"

  - name: Lenovo | Precheck redfish login
    community.general.xcc_redfish_command:
      category: Raw
      command: GetResource
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      resource_uri: "/redfish/v1/Systems/1"
      timeout: 20
    when: inventory_hostname in groups['lenovo']

  - name: Dell | Precheck redfish login
    community.general.idrac_redfish_info:
      category: Manager
      command: GetManagerAttributes
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      timeout: 20
    when: inventory_hostname in groups['dell']
  tags:
  - pre-check

- hosts: all
  name: Mount  {{ image_url }} ISO
  gather_facts: false
  tasks:
  - name: Check {{ image_url }} ISO file exists
    shell: "curl -sI {{ image_url }}"
    register: response
    failed_when: "'200 OK' not in response.stdout or '404 Not Found' in response.stdout"
    tags:
    - mount-iso

  - name: Dell | Set iDRAC virtual media attach attribute to attached
    community.general.idrac_redfish_config:
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      category: "Manager"
      command: "SetManagerAttributes"
      manager_attributes:
        VirtualMedia.1.Attached: "Attached"
    when:
    - inventory_hostname in groups['dell']
    tags:
    - mount-iso

  - name: Get virtual media details
    community.general.redfish_info:
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      category: "Manager"
      command: "GetVirtualMedia"
    register: result
    tags:
    - mount-iso
    - umount-iso
    when:
    - inventory_hostname not in groups['lenovo']

  - name: Lenovo | Eject all Virtual Media
    community.general.xcc_redfish_command:
      category: Manager
      command: VirtualMediaEject
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      resource_id: "1"
    when:
    - inventory_hostname in groups['lenovo']
    tags:
    - mount-iso
    - umount-iso

  - name: Eject virtual media
    community.general.redfish_command:
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      category: "Manager"
      command: "VirtualMediaEject"
      virtual_media:
        image_url: "{{ item }}"
    with_items: "{{ result.redfish_facts.virtual_media.entries[0][1] | selectattr('ConnectedVia', 'equalto','URI') | map(attribute='Image') | list }}"
    when:
    - inventory_hostname not in groups['lenovo']
    tags:
    - mount-iso
    - umount-iso

  - name: Insert {{ image_url }} ISO as virtual media device
    community.general.redfish_command:
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      category: "Manager"
      command: "VirtualMediaInsert"
      virtual_media:
        image_url: "{{ image_url }}"
        media_types:
          - CD
          - DVD
    when:
    - inventory_hostname not in groups['lenovo']
    tags:
    - mount-iso

  - name: Lenovo | Insert {{ image_url }} Virtual Media
    community.general.xcc_redfish_command:
      category: Manager
      command: VirtualMediaInsert
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      virtual_media:
        image_url: "{{ image_url }}"
        media_types:
          - CD
          - DVD
      resource_id: "1"
    when:
    - inventory_hostname in groups['lenovo']
    tags:
    - mount-iso

  - name:  Dell | set iDRAC attribute for one-time boot from virtual CD
    community.general.idrac_redfish_config:
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      category: "Manager"
      command: "SetManagerAttributes"
      manager_attributes:
        ServerBoot.1.BootOnce: "Enabled"
        ServerBoot.1.FirstBootDevice: "VCD-DVD"
    when:
    - inventory_hostname in groups['dell']
    tags:
    - mount-iso

  - name: Set one-time boot device to {{ bootdevice }}
    community.general.redfish_command:
      category: Systems
      command: SetOneTimeBoot
      bootdevice: "{{ bootdevice }}"
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      timeout: 20
    when:
    - inventory_hostname not in groups['dell']
  tags:
  - mount-iso

- hosts: all
  name: Power Force Restart the host
  gather_facts: false
  tasks:
  - name: Turn system power on
    community.general.redfish_command:
      category: Systems
      command: PowerOn
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
  - name: Reboot system
    community.general.redfish_command:
      category: Systems
      command: PowerForceRestart
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      timeout: 20
  tags:
  - reboot

- hosts: all
  name: Wait for the ESXi OS installation to complete
  gather_facts: false
  vars:
    esxi_username: "root"
    govc_url: "https://{{ esxi_username }}:{{ esxi_password }}@{{ esxi_address }}"
  tasks:
  - name: "Wait for {{ inventory_hostname }} install ESXi {{ esxi_address }} host to be complete"
    shell: "govc about -k=true -u={{ govc_url}}"
    retries: 60
    delay: 30
    register: result
    until: result.rc == 0
  tags:
  - post-check
